<?php
/**
 * $Id$
 * phpframework - v1.0 - http://www.cuatrovientos.org
 * Pello Xabier Altadill Izura - Instituto Cuatrovientos 
 * data.inc
 * Toda la lógica de acceso a datos
 * 
 * Clase que contiene un result set Mapeado.
 */ 


class Data {

  var $id;	// Identificador
  var $fields = ""; // Campos: indice=nombre_de_campo. valor=numero
  var $field_index = ""; // Campos: indice=numero. valor=nombre_de_campo
  var $matrix = NULL; // Datos
  var $index = 0;

	/**
	* constructor
	*/
	function Data () {
		$this->index = 0;
	}

	/**
	* data2XML
	* convierte el result set a un fichero XML
	*/
	function data2XML () {
	}
	
	/**
	* data2Table
	* convierte el result set a una tabla HTML
	*/
	function data2Table ($fields=array(),$link_fields=array(),$linked_text=array(),$css="") {
		$html_code = "\n<!-- Dinamic table - Generated by phpframework - www.cuatrovientos.org -->\n<table class='$css' cellspacing='0' cellspadding='0'>";

		// Poner cabecera
		$html_code .= "<tr>\n";
		if (!sizeof($fields)) {
			$names = array_keys($this->fields);
			for ($i=0;$i<sizeof($names);$i++) {
				$html_code .= "\t<th>".$names[$i]."</th>\n";
			}
		} else {			
			for ($i=0;$i<sizeof($fields);$i++) {
				$html_code .= "\t<th>".$fields[$i]."</th>\n";
			}
		}
		$html_code .= "</tr>\n";

		//Poner datos
			$this->reset();
			while ($this->hasMoreElements()) {
				$html_code .= "<tr>\n";
				$temp_array = $this->matrix[$this->index];
				$tam = (sizeof($temp_array)/2);
				for ($i=0;$i<$tam;$i++) {
					$html_code .= "\t<td>&nbsp;".$temp_array[$i]."</td>\n";
				}
				$html_code .= "</tr>\n";
				$this->next();
			}
				
		$html_code .= "</table>\n<!-- Dinamic table - Table end - Generated by phpframework - www.cuatrovientos.org  -->\n";
		// Finalmente, retornamos el codigo HTML generado
		return $html_code;
	}

	/**
	* data2PagedTable
	* convierte el result set a una tabla HTML con paginacion
	* el primer campo en la select debe ser un codigo.
	*/
	function data2PagedTable ($fields=array(),$link_fields=array(),$linked_text="", $order_link="",$order="",$ord="DESC",$cambiar=0,$css="",$total=0,$limit=0,$offset=0,$key="") {

		include_once "./lib/crypter.inc.php";
		$cifrador = new Crypter($key);
		
		$c = 1;

		if ($cambiar) {
			$ord = ($ord=="DESC" || $ord=="")?"ASC":"DESC";
		} else {
			$ord = "DESC";
		}
	
			$html_code = "\n<center><!-- Dinamic table - Generated by phpframework - www.cuatrovientos.org -->\n<table class='$css' cellspacing='0' cellspadding='0'>";

		// Poner cabecera
		$html_code .= "<tr><th></th>\n";
		$names = array_keys($this->fields);

		if (!sizeof($fields)) {
			for ($i=1;$i<sizeof($names);$i++) {
				$html_code .= "\t<th><a href='/?".$cifrador->encrypt($order_link.$names[$i]."&cambiar=1&ord=".$ord)."'>".$names[$i]."</a></th>\n";
			}
		} else {			
			for ($i=0;$i<sizeof($fields);$i++) {
				$html_code .= "\t<th><a href='/?".$cifrador->encrypt($order_link.$names[$c++]."&cambiar=1&ord=".$ord)."'>".$fields[$i]."</a></th>\n";
			}
		}
		$html_code .= "</tr>\n";

		//Poner datos: atencion, el primero campo debe ser el codigo
			$this->reset();
			while ($this->hasMoreElements()) {
				$temp_array = $this->matrix[$this->index];
				$tam = (sizeof($temp_array)/2);
				$html_code .= "\n <tr>";
				$html_code .= "\t<td style='background:white' valign='center'><a href='/?".$cifrador->encrypt($linked_text."&ac=Delete&cod=".$temp_array[0])."'>"."<img border='0' src='images/emblem-noread.png' alt='Eliminar postit' title='Eliminar postit'>"."</a></td>";

				for ($i=1;$i<$tam;$i++) {
					$html_code .= "<td><a href='/?".$cifrador->encrypt($linked_text."&ac=ViewDetail&cod=".$temp_array[0])."' title='ver detalle' alt='ver detalle'>".(($temp_array[$i]!="")?$temp_array[$i]:"&nbsp;")."</a></td>\n";
				}

				$html_code .= "</tr>\n";
				$this->next();
			}
				
		$html_code .= "</table>\n";
		
		$limit = (!$limit || $limit=="")?10:$limit;
//		echo "Total: " . $total;
		// Preparamos la paginacion
		$final = ($total>10)?($total - 10):0;
		$anterior = (!$offset || $offset=="" || $offset<$limit)?0:($offset-10);
		$siguiente = (($offset+10)>=$total)?$final:($offset+10);
		
		$enlaces[0] = "<a href='/?".$cifrador->encrypt($order_link.$order."&ord=".$ord."&limit=".$limit."&offset=0")."'><img src='images/pag-inicial.png' alt='Inicio' title='Inicio' border='0' /></a>";
		$enlaces[1] = "<a href='/?".$cifrador->encrypt($order_link.$order."&ord=".$ord."&limit=".$limit."&offset=".$anterior)."'><img src='images/pag-anterior.png' alt='Anterior' title='Anterior' border='0' /></a>";
		$enlaces[2] = "<a href='/?".$cifrador->encrypt($order_link.$order."&ord=".$ord."&limit=".$limit."&offset=".$siguiente)."'><img src='images/pag-siguiente.png' alt='Siguiente' title='Siguiente' border='0' /></a>";
		$enlaces[3] = "<a href='/?".$cifrador->encrypt($order_link.$order."&ord=".$ord."&limit=".$limit."&offset=".$final)."'><img src='images/pag-final.png' alt='Final' title='Final' border='0' /></a>";
		$html_code .= "<table><tr><td>".$enlaces[0]."</td><td>".$enlaces[1]."</td><td>".$enlaces[2]."</td><td>".$enlaces[3]."</td></tr></table></center>\n<!-- Dinamic table - Table end - Generated by phpframework - www.cuatrovientos.org  -->\n";
	
		// Finalmente, retornamos el codigo HTML generado
		return $html_code;
	}


	/**
	* data2Register
	* convierte el result set a una tabla HTML de un unico campo
	*/
	function data2Register ($title="",$css="",$fields=array(),$link_fields=array(),$linked_text=array()) {
		$html_code = "\n<!-- Dinamic table - Generated by phpframework - www.cuatrovientos.org -->\n";

		// le damos un estilos por defecto
		$clase = ($css!="")?$css:"tbregistro";
		
		// Poner cabecera
		$html_code .= "<table class='".$clase."' border='0' cellspacing='0' cellspadding='0'>";
		$html_code .= "<tr><th colspan=2>".$title."</th></tr>\n";

		//Poner datos. Se supone que solo hay un registro
			$this->reset();
				$temp_array = $this->matrix[0];
				$len = (sizeof($temp_array)/2);
				$html_code .= "<!-- ".sizeof($temp_array)."-->";
				for ($i=0;$i<$len;$i++) {
					$html_code .= "\t<tr><td class='campo'>".$this->getField($i)."</td><td  class='dato'>&nbsp;".$temp_array[$i]."</td></tr>\n";
				}
				
		$html_code .= "</table><!-- Dinamic table - Table end - Generated by phpframework - www.cuatrovientos.org -->\n";
		// Finalmente, retornamos el codigo HTML generado
		return $html_code;
	}

	/**
	* data2Select
	* convierte el result set a una lista HTML
	*/
	function data2Select ($value,$option,$name="select",$selected_value="",$multiple=0, $js="",$inicial="") {
		$esmultiple = ($multiple==0)?"":"multiple size='".$multiple."'";
		$html_code = "\n<!-- Dinamic select - Generated by phpframework - www.cuatrovientos.org -->\n";
		
		$html_code = "\n<select id='". $name ."' name='". $name ."' ". $esmultiple . " " .$js. "><option></option>\n";
		$selected = "";
		//Poner datos
		$this->reset();
//			echo " Total: " . $this->length() ."<br>\n";
//			echo " Valor: ". count($this->matrix). "<br>\n";
		
		$html_code .= ($inicial != "")?"\n\t<option value='-1'>".$inicial."</option>\n":"";
		
		while ($this->hasMoreElements()) {
			$selected = ($this->getValue($value) == $selected_value)?'selected':"";
//			echo " <!-- ".$this->getValue($value)." va [".$selected_value."] $value $option-->\n";
			$html_code .= "\t<option value='".$this->getValue($value)."' ".$selected.">".$this->getValue($option)."</option>\n";
			$this->next();
		}
				
		$html_code .= "\n</select>\n<!-- Dinamic select - Table end - Generated by phpframework - www.cuatrovientos.org -->\n";
		// Finalmente, retornamos el codigo HTML generado
		return $html_code;
	}


	/**
	* data2Modify
	* convierte el result set a un formulario de modificacion
	*/
	function data2Modify ($title="",$css="",$form_action="") {

		$html_code = ""; // Codigo HTML final
	  	$html_code .= "<h4>$title</h4>";
		$html_code .= "<form name='modificar' action='$form_action' method='post'>\n";
		$html_code .= "<table cellspacing=0 cellspadding=0>\n";

	        for ($i=0;$i<sizeof($this->field_index);$i++) {
        	        $html_code .="<tr><td><b>".$this->field_index[$i]."</b></td><td><input type='text' name='$i' 
					value='".$this->matrix[0][$this->field_index[$i]] ."' size=30></td></tr>\n";
	        }

		$html_code .= "</table><input type='submit' value='Submit'><input type='button' name='rst' 
				value='&lt;&lt;' onclick='history.back()'></form>\n";

		$html_code .= "<!-- Dinamic select - Table end - Generated by phpframework -->\n";
		return $html_code;
        }


/**
	* data2Checkbox
	* convierte el result set a una lista de resultados seleccionables
	* y clickables 
	*/
	function data2Checkbox ($value,$name,$linkto,$detaillink="", $selected_value="",$key="") {

		include_once "./lib/crypter.inc.php";
		$cifrador = new Crypter($key);

		$enlace = "";
		$enlacedetalle = "";
		$nombrecampo = $cifrador->encrypt("nombre")."[]";

		$html_code = "\n<!-- Dinamic checkbox list - Generated by phpframework - www.cuatrovientos.org -->\n";
		$html_code .= "\n<table border='0'>";

		//Poner datos
		$this->reset();
		while ($this->hasMoreElements()) {
			$enlace = $cifrador->encrypt($linkto."cod=" . $this->getValue($value));
			$enlacedetalle = $cifrador->encrypt($detaillink."cod=" . $this->getValue($value));
			$html_code .= "<tr><td><input type='checkbox' name='".$nombrecampo."' value='".$this->getValue($value)."'>&nbsp;";
			$html_code .= "<a href='/?" . $enlace . "'>".$this->getValue($name)."</a></td>\n";
			$html_code .= "<td style='font-size:9pt'>&nbsp;&nbsp;(<a href='/?" . $enlacedetalle . "'>Detalle...</a>)</td></tr>\n";
			//$selected = ($this->getValue[$option] == $selected_value)?'selected':"";
			$this->next();
		}
				
		$html_code .= "\n</table>\n<!-- Dinamic select - Table end - Generated by phpframework - www.cuatrovientos.org -->\n";
		// Finalmente, retornamos el codigo HTML generado
		return $html_code;
	}
	
	/**
	* data2List
	* convierte el result set a una lista
	*/
	function data2List ($value,$value2 ) {

		$html_code = "\n<!-- Dinamic list - Generated by phpframework - www.cuatrovientos.org -->\n";
		$html_code .= "\n<ul>";

		//Poner datos
		$this->reset();
		while ($this->hasMoreElements()) {
			$html_code .= "<li>" . $this->getValue($value) . " ".$this->getValue($value2)."</li>\n";
			$this->next();
		}
				
		$html_code .= "\n</ul>\n<!-- Dinamic list - end - Generated by phpframework - www.cuatrovientos.org -->\n";
		// Finalmente, retornamos el codigo HTML generado
		return $html_code;
	}
	
	/**
	* setFields
	* establecemos el valor fields
	*/
	function setFields ($fields_array) {
		$this->fields =  $fields_array;
		$this->field_index = array_keys($fields_array);
	}

	/**
	* next
	* pasamos al siguiente registro
	*/
	function next () {
		$this->index = $this->index + 1;
	}

	/**
	* reset
	* pasamos al primer registro
	*/
	function reset () {
		$this->index = 0;
	}

	/**
	* hasMoreElements
	* condicion para decir si tiene mas elementos
	*/
	function hasMoreElements () {
		return ($this->index < $this->length());
	}

	/**
	* length
	* Numero de registros del ResultSet
	*/
	function length () {
	 return (count($this->matrix));
	}

	/**
	* getValue
	* Toma un dato concreto del resultset
	*/
	function getValue ($field) {
	 return $this->matrix[$this->index][$this->fields[$field]];
	}
	
	/**
	* getValue
	* Establece dato concreto del resultset
	*/
	function setValue ($field, $value) {
	 $this->matrix[$this->index][$this->fields[$field]] = $value;
	}

	/**
	* getField
	* Dado un indice de campo de registro devuelve el nombre de ese campo
	*/
	function getField ($index) {
	 return $this->field_index[$index];
	}

	/**
	* dump
	* Vuelca en un string todo el contenido
	*/
	function dump () {
	 $result= "";
	 return $result;
	}
	
}	
?>
